import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@pheralb/toast";
import "./globals.css";
import { XIcon } from "lucide-react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {/* Contenido principal */}
                <div className="flex flex-col flex-1 min-h-dvh">
                    {/* <Navbar /> */}
                    <main className="flex-1 overflow-y-scroll bg-dark">
                        {children}
                        <Toaster
                            position="bottom-right"
                            toastOptions={{
                                animationOnClose: "swipe",
                                defaultCloseContent: <XIcon />,
                                classNames: {
                                    toast: "toast-dark",
                                }
                            }}
                        />
                    </main>
                </div>
            </body>
        </html>
    );
}
